name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # O la rama en la que deseas que se ejecute el flujo de trabajo.
  workflow_dispatch:  # Permite ejecutar manualmente el flujo de trabajo.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.igneaxx }}
          password: ${{ secrets.Aylin2024! }}

      - name: Build Docker image
        run: docker build . -t igneaxx/EST-MET:latest

      - name: Push Docker image
        run: docker push igneaxx/EST-MET:latest
